export type Games = {
    id: string,
    name: string,
    description: string,
    released: string,
    price : number,
    image: string,
    tags: string,
    windows: boolean,
    mac: boolean,
    linux: boolean,
    developers: string,
    publishers: string,
    categories: string,
    genres: string,
    positive: number,
    negative: number,
    requiredAge: number,
    supportURL: string,
    supportEmail: string,
    website: string,
    screenshots: string,
    movies: string,
    reviews: string,
    supportedLanguages: string

}